export const enum ControlName {
  ShowSuggest = 'showSuggest',
  WorkbenchCssPath = 'workbenchCssPath',
  Gradient = 'gradient',
  GradientBrightness = 'gradientBrightness',
  GradientDarkness = 'gradientDarkness',
  HashSource = 'hashSource',
  Refresh = 'refresh',
  RandomColor = 'randomColor',
  'RandomColor.colorSet' = 'randomColor.colorSet',
  'RandomColor.pure' = 'randomColor.pure',
  'RandomColor.specify' = 'randomColor.specify',
  ProjectIndicators = 'projectIndicators',
  ThemeColors = 'themeColors',
}
