import vscode from 'vscode';

export const Msg = (() => {
  const Zh = {
    NoMoreInfoPop: '不再提示',
    NoMoreInfoPopSet: '如果手动开启了提示，需重启VS Code后生效',
    NotWorkspace: '没有打开工作区文件夹，不改变标题栏颜色',
    NotProject: '当前不是项目目录，不改变标题栏颜色',

    Commands: {
      enableGradient: {
        prompt: '启用渐变色标题栏需要修改workbench.desktop.main.css，请提供该文件地址',
        workbenchCssPathInvalid: 'workbench.desktop.main.css 路径无效，请检查',
      },
      disableGradient: '',
    },

    ConfigLevel: {
      [vscode.ConfigurationTarget.Workspace]: '工作区',
      [vscode.ConfigurationTarget.WorkspaceFolder]: '工作区文件夹',
      [vscode.ConfigurationTarget.Global]: '全局',
    },

    // 设置标题栏颜色
    TitleBarColorSet: (settingsCreated: boolean) =>
      `标题栏颜色已更新${settingsCreated ? '，已创建settings.json' : ''}`,

    // 设置全局标题栏样式
    NotCustomTitleBarStyle: (level: string) =>
      `检测到"${level}"级别的标题栏样式设置不是"custom"，需要设置为"custom"本插件才能生效`,
    SetTitleBarStyleToCustom: '帮我设置好',
    Cancel: '还是算了',
    SetTitleBarStyleToCustomSuccess: '标题栏样式已设置为custom，重启VS Code后生效',
  };

  const En = {
    NoMoreInfoPop: 'Do not show this again',
    NoMoreInfoPopSet: 'If you set "showInfoPop" to "true", please restart VS Code to make it work',
    NotWorkspace: 'No workspace folder opened, titlebar color remains unchanged',
    NotProject: 'Current folder is not a project directory, titlebar color remains unchanged',

    Commands: {
      enableGradient: {
        prompt: '启用渐变色标题栏需要修改workbench.desktop.main.css，请提供该文件地址',
        workbenchCssPathInvalid:
          'The path to "workbench.desktop.main.css" is invalid, please check',
      },
      disableGradient: 'Turn off gradient titlebar',
    },

    ConfigLevel: {
      [vscode.ConfigurationTarget.Workspace]: 'Workspace',
      [vscode.ConfigurationTarget.WorkspaceFolder]: 'Workspace Folder',
      [vscode.ConfigurationTarget.Global]: 'Global',
    },

    // 设置标题栏颜色
    TitleBarColorSet: (settingsCreated: boolean) =>
      `TitleBar color has been updated${
        settingsCreated ? ', "settings.json" has been created' : ''
      }`,

    // 设置全局标题栏样式
    NotCustomTitleBarStyle: (level: string) =>
      `Detected "${level}" level "titleBarStyle" setting is not "custom", it needs to be "custom" for this extension to take effect`,
    SetTitleBarStyleToCustom: 'Set it for me',
    Cancel: 'Not now',
    SetTitleBarStyleToCustomSuccess:
      '"titleBarStyle" has been set to custom, Please restart VS Code to make it work',

    // 设置标题颜色
    SettingsFileMightBeGenerated: 'The settings file might be generated by this extension',
  };

  const isChinese = vscode.env.language.toLowerCase().startsWith('zh');
  return isChinese ? Zh : En;
})();
